name: weru_digital
description: "Weru Digital - Radio, TV and News App"

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none"

version: 3.0.3+5

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.1
  google_fonts: ^6.1.0
  just_audio: ^0.10.4
  audio_session: ^0.2.2
  webview_flutter: ^4.4.2
  webview_flutter_android: ^4.7.0
  http: ^1.1.2
  xml: ^5.4.1
  webfeed: ^0.7.0
  url_launcher: ^6.2.2
  cached_network_image: ^3.3.0
  intl: ^0.17.0
  share_plus: ^11.0.0
  package_info_plus: ^8.3.0
  flutter_html: ^3.0.0-beta.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
